### ISSUE TITLE
function Int to string

### ISSUE THREAD

**Issue by raph-amiard** [raph-amiard/cours-ada-epita#3]
Ecrire une fonction qui convertit un Integer en String (sans utiliser 'Image).  Traiter d'abord les entier positifs, puis tous les entiers signes. Tester avec différentes valeurs.

**Comment by Tauril** [comment]
```ada
function Itoa (I : Integer) return String is
    function Itoa_Rec (I : Integer) return String is
      C : Character;
    begin
      if I < 0 then
        return Itoa_Rec(-I);
      elsif I < 10 then
        return Character'Val(I + 48) & "";
      end if;
      -- 48: '0'
      C := Character'Val((I mod 10) + 48);
      return C & Itoa_Rec(I / 10);
    end Itoa_Rec;
    Rev : String := Itoa_Rec(I);
    Ret : String (Rev'Range);
begin
    for J in reverse Rev'Range loop
      Ret (Rev'Last - J + Ret'First) := Rev (J);
    end loop;
    if I < 0 then
      return "-" & Ret;
    end if;
    return Ret;
end Itoa;
```

**Comment by M4R5** [comment]
function itoa(i : integer) return string is
    function revertrim(str : string; len : integer) return string is
        res : string(1 .. len);
    begin
        for i in res'range loop
            res(res'last - i + str'first) := str(i);
        end loop;
        return res;
    end;

    str_res : string(1..1024);
    int_tmp : integer := (if i < 0 then -i else i);
    it : integer := str_res'first;
begin
    while int_tmp > 0 loop
        str_res(it) := character'val(int_tmp mod 10 + character'pos('0'));
        int_tmp := int_tmp / 10;
        it := it + 1;
    end loop;

    if i < 0 then
        str_res(it) := '-';
        it := it + 1;
    end if;

    return revertrim(str_res, it - 1);
end itoa;

**Comment by raph-amiard** [comment]
```ada
with Ada.Text_IO; use Ada.Text_IO;

procedure Itos is

   Digit_To_Char : array (0 .. 9) of Character :=
      (0 => '0', 1 => '1', 2 => '2', 3 => '3', 4 => '4',
       5 => '5', 6 => '6', 7 => '7', 8 => '8', 9 => '9');

   function I_To_S (I : Integer) return String is 
   begin
      return 
         (if I < 0
          then "-" & I_To_S (-I)
          elsif I < 10
          then ""
          else I_To_S (I / 10)) & Digit_To_Char (I mod 10);
   end I_To_S;

begin
   Put_Line (I_To_S (129439));
end Itos;
```

**Comment by raph-amiard** [comment]
```ada
with Ada.Text_IO; use Ada.Text_IO;

procedure Itos is
   function Itos (I : Integer) return String is
      Buffer      : String (1 .. 10);
      Temp        : Integer := I;
      Start_Index : Positive;
   begin
      for I in reverse Buffer'Range loop
         Buffer (I) := Character'Val(Character'Pos ('0') + Temp mod 10);
         Temp := Temp / 10;
         if Temp = 0 then
            Start_Index := I;
            exit;
         end if;
      end loop;
      return Buffer (Start_Index .. Buffer'Last);
   end Itos;
begin
   Put_Line (Itos (125503));
end Itos;
```

**Comment by RobinDuprat** [comment]
-- Log package                                                                  
with Ada.Numerics.Elementary_Functions; use Ada.Numerics.Elementary_Functions;  
                                                                                
--------------------------------------------------------------------------------
-- PACKAGE BODY - Convert                                                       
---------------------------------------------------------------------------     
package body Convert is                                                         
  function intToString (N_IN : Integer) return String is                        
    N : Integer := N_IN;                                                        
    S : String (1..Integer(log(abs(Float(N)) + 0.1)));                          
    I : Integer := S'Last;                                                      
  begin                                                                         
    if N = 0 then -- 0 / Integer'First case                                     
      return " 0";                                                              
    elsif N_IN = Integer'First then -- use to avoid abs(Integer'First) overflow 
      N := abs(N + 1);                                                          
    elsif N < 0 then                                                            
      N := abs(N);                                                              
    end if;                                                                     
    while N > 0 loop -- transform digit in characters                           
      S(I) := Character'Val(Character'Pos('0') + N mod 10);                     
      N := N / 10;                                                              
      I := I - 1;                                                               
    end loop;                                                                   
    if N_IN < 0 then -- negative case                                           
      S(I) := '-';                                                              
    else                                                                        
      S(I) := ' ';                                                              
    end if;                                                                     
    if N_IN = Integer'First then -- add +1 if avoiding Integer'First overflow   
      S(S'Last) := Character'Val(Character'Pos(S(S'LAST)) + 1);                 
    end if;                                                                     
    return S(I..S'Last);                                                        
  end intToString;                                                              
end Convert;
